### ISSUE TITLE
RT Error on new Source

### ISSUE THREAD

**Issue by hondrogiannis** [vdelachaux/4DPop-Git#10]
RT Error

open the source of the 4DPop-Git-18R3 component with 4D v18r3

Executing the method "4DPop_GIT" .

The dialog opens "4DPop GIT" .

when I double click on "Remotes" I get the following RT error. 

<img width="687" alt="4DGit_debug_1" src="https://user-images.githubusercontent.com/63335321/85341826-67cba380-b4e9-11ea-896c-b62989b00e0e.png">
<img width="1166" alt="4DGit_debug_2" src="https://user-images.githubusercontent.com/63335321/85341829-6ac69400-b4e9-11ea-8515-02ee8c64918b.png">
<img width="1307" alt="4DGit_debug_3" src="https://user-images.githubusercontent.com/63335321/85341832-6bf7c100-b4e9-11ea-88a4-e225f00ca595.png">

**Comment by vdelachaux** [comment]
Thanks. It's fixed in the latest version
