### ISSUE TITLE
Detection of git repository?

### ISSUE THREAD

**Issue by mesopelagique** [vdelachaux/4DPop-Git#3]
I see that using a base under a subfolder like that
https://github.com/mesopelagique/Examples-Pattern/

That I have the message "This database is not under git source control"
Its because`.git` folder not exists at this level, but in parent folder

Some software detect that, some not

The more simple is to display a different message like "This database is under git source control but not at this level" "Initialize git repository here anyway" if git status or git log success 

The more complicated is to support any git level repo. checking parent dir recursively, keeping a rootFolder instead of database folder for all other git command

**Comment by vdelachaux** [comment]
From now, the search of a git repository is performed in parent folders.
So, if a .git  folder exists in a parent folder, as suggested, a different message is displayed.
