### ISSUE TITLE
Error on git path: folder vs file

### ISSUE THREAD

**Issue by mesopelagique** [vdelachaux/4DPop-Git#4]
When clinking on one folder I have an error  on https://github.com/vdelachaux/4DPop-Git/blob/5e8ce646d6755bde73a2af645da46d25cee762d0/Project/Sources/Methods/GIT%20Path.4dm#L92 maybe because it is a Folder and not a File
![Screenshot 2020-04-16 at 22 40 47](https://user-images.githubusercontent.com/59135882/79504621-77cf8e80-8033-11ea-8995-b64321d4e592.png)

**Comment by vdelachaux** [comment]
fixed
