### ISSUE TITLE
RELOAD PROJECT and 4D v18r3

### ISSUE THREAD

**Issue by hondrogiannis** [vdelachaux/4DPop-Git#8]
Hi, 
in the **GIT** method, the RELOAD PROJECT call on line 122 must be executed using **EXECUTE FORMULA** to be compatible with 4D v18r3.

If(Num(Application version)>=1840) //#18R4+									
  EXECUTE FORMULA("RELOAD PROJECT:C1739")
end-if 

regards
Nikolaos Hondrogiannis

**Comment by hondrogiannis** [comment]
the component requires version 4D v18r4

The 4D commands
**Generate digest**
**BASE64 DECODE**

are called with new parameters, which are not yet available in version 4D v18r3

**Comment by vdelachaux** [comment]
Thank you for pointing out these errors.
I have created a new branch for the 18R3 and updated the readme to alert the users
